[package]
name = "aoc2019"
version = "0.1.0"
authors = ["DeltaPHC <phclem@protonmail.com>"]
edition = "2018"

[dependencies]
aoc-helper = { git = "https://github.com/cubetastic33/aoc-helper", rev = "69447645dba8b6190dcec43a91557f0175642217" }
itertools = "0.8"
petgraph = "0.4.13"
